// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: bancaQueries_manual.sql

package sqlBanca

import (
	"context"
	"database/sql"
)

const insertDeleteTT = `-- name: InsertDeleteTT :one
DECLARE @InsertedData TABLE (BatchId int
		, Jenis tinyint
		, UserInput int
		, UserOtor int
		, DateOtor datetime
		, StatusOtor tinyint
		, ActionType varchar(10)
		);

INSERT INTO BancaDelete_TT
	(Jenis, UserInput, StatusOtor, ActionType)
OUTPUT inserted.BatchId, inserted.Jenis
		, inserted.UserInput, inserted.UserOtor
		, inserted.DateOtor, inserted.StatusOtor 
		, inserted.ActionType
			INTO @InsertedData
VALUES(@p1, @p2, @p3, @p4)

SELECT BatchId, Jenis, UserInput
		, UserOtor, DateOtor, StatusOtor,ActionType
FROM @InsertedData;
`

type InsertDeleteTTParams struct {
	Jenis      int32    `json:"jenis"`
	Userinput  int32          `json:"userinput"`
	Statusotor int32    `json:"statusotor"`
	Actiontype sql.NullString `json:"actiontype"`
}

func (q *Queries) InsertDeleteTT(ctx context.Context, arg InsertDeleteTTParams) (BancadeleteTt, error) {
	row := q.db.QueryRowContext(ctx, insertDeleteTT,
		arg.Jenis,
		arg.Userinput,
		arg.Statusotor,
		arg.Actiontype,
	)
	var i BancadeleteTt
	err := row.Scan(
		&i.Batchid,
		&i.Jenis,
		&i.Userinput,
		&i.Userotor,
		&i.Dateotor,
		&i.Statusotor,
		&i.Actiontype,
	)
	return i, err
}

const getBancaControlTableTMLastId = `-- name: GetBancaControlTableTM :one
	DECLARE  @outPreviousDate			smalldatetime
			,@outCurrentDate			smalldatetime
			,@outNextDate				smalldatetime
			,@outBeginOfDay				bit
			,@outEndOfDay				bit
			,@outLastBatchId			bigint
			,@outBatchProcessBit		bit
			,@outGNCAccountNoIDR		varchar(20)
			,@outGLAccountFeeAccruedIDR	varchar(20)
			,@outGLOwnerFee				varchar(20)
			,@outOwnerBranch			int
			,@outGNCPerantaraTravelex	varchar(20)
			,@outIsAAJIMandatory		bit
			,@outIsAAUIMandatory		bit
			,@outOnOffBancaGW			bit
			,@outOnOffBMWGLOLLog		bit
			,@outGLFeeValas				varchar(20)
			,@outGLFeeValasBranch		varchar(20)

	UPDATE BancaControlTable_TM  
	SET		@outPreviousDate			= PreviousDate			
		,@outCurrentDate				= CurrentDate			
		,@outNextDate				= NextDate				
		,@outBeginOfDay				= BeginOfDay				
		,@outEndOfDay				= EndOfDay				
		,@outLastBatchId				= LastBatchId			
		,@outBatchProcessBit			= BatchProcessBit		
		,@outGNCAccountNoIDR			= GNCAccountNoIDR		
		,@outGLAccountFeeAccruedIDR	= GLAccountFeeAccruedIDR	
		,@outGLOwnerFee				= GLOwnerFee				
		,@outOwnerBranch				= OwnerBranch			
		,@outGNCPerantaraTravelex	= GNCPerantaraTravelex	
		,@outIsAAJIMandatory			= IsAAJIMandatory		
		,@outIsAAUIMandatory			= IsAAUIMandatory		
		,@outOnOffBancaGW			= OnOffBancaGW			
		,@outOnOffBMWGLOLLog			= OnOffBMWGLOLLog		
		,@outGLFeeValas				= GLFeeValas				
		,@outGLFeeValasBranch		= GLFeeValasBranch	
		,LastBatchId					= LastBatchId +1


	SELECT  @outPreviousDate			AS PreviousDate			
		,@outCurrentDate				AS CurrentDate			
		,@outNextDate				AS NextDate				
		,@outBeginOfDay				AS BeginOfDay				
		,@outEndOfDay				AS EndOfDay				
		,@outLastBatchId				AS LastBatchId			
		,@outBatchProcessBit			AS BatchProcessBit		
		,@outGNCAccountNoIDR			AS GNCAccountNoIDR		
		,@outGLAccountFeeAccruedIDR	AS GLAccountFeeAccruedIDR	
		,@outGLOwnerFee				AS GLOwnerFee				
		,@outOwnerBranch				AS OwnerBranch			
		,@outGNCPerantaraTravelex	AS GNCPerantaraTravelex	
		,@outIsAAJIMandatory			AS IsAAJIMandatory		
		,@outIsAAUIMandatory			AS IsAAUIMandatory		
		,@outOnOffBancaGW			AS OnOffBancaGW			
		,@outOnOffBMWGLOLLog			AS OnOffBMWGLOLLog		
		,@outGLFeeValas				AS GLFeeValas				
		,@outGLFeeValasBranch		AS GLFeeValasBranch	
`

func (q *Queries) GetBancaControlTableTMLastId(ctx context.Context) (BancacontroltableTm, error) {
	row := q.db.QueryRowContext(ctx, getBancaControlTableTMLastId)
	var i BancacontroltableTm
	err := row.Scan(
		&i.Previousdate,
		&i.Currentdate,
		&i.Nextdate,
		&i.Beginofday,
		&i.Endofday,
		&i.Lastbatchid,
		&i.Batchprocessbit,
		&i.Gncaccountnoidr,
		&i.Glaccountfeeaccruedidr,
		&i.Glownerfee,
		&i.Ownerbranch,
		&i.Gncperantaratravelex,
		&i.Isaajimandatory,
		&i.Isaauimandatory,
		&i.Onoffbancagw,
		&i.Onoffbmwglollog,
		&i.Glfeevalas,
		&i.Glfeevalasbranch,
	)
	return i, err
}