// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: refundBillingQueries_manual.sql

package sqlBanca

import (
	"context"
)

const execBASelectRefundBilling = `-- name: ExecBASelectRefundBilling :many
exec BA_SelectRefundBilling @p1
`

type ExecSPBASelectRefundBillingParams struct {
	SPAJId string `json:"spajId"`
}

type ExecSPBASelectRefundBillingRow struct {
	Pilih					string `json:"Pilih"`
	BillingTransactionGuid	string `json:"BillingTransactionGuid"`
	SPAJNo					string `json:"SPAJNo"`
	BillingBatchId			string `json:"BillingBatchId"`
	BillingNo				string `json:"BillingNo"`
	BillingDescription		string `json:"BillingDescription"`
	TransactionType			string `json:"TransactionType"`
	TransactionDate			string `json:"TransactionDate"`
	NominalBilling			string `json:"NominalBilling"`
	TotalFee				string `json:"TotalFee"`
	FeeBasedNISP			string `json:"FeeBasedNISP"`
	StatusBilling			string `json:"StatusBilling"`
	BillingRemarks			string `json:"BillingRemarks"`
	ProductCode				string `json:"ProductCode"`
	BranchId				string `json:"BranchId"`
	FeeBatchId				string `json:"FeeBatchId"`
	FeeTransactionDate		string `json:"FeeTransactionDate"`
	FeeStatus				string `json:"FeeStatus"`
}

// func (q *Queries) ExecBASelectRefundBilling(ctx context.Context, baSelectrefundbilling interface{}) (sql.Result, error) {
// 	return q.db.ExecContext(ctx, execBASelectRefundBilling, baSelectrefundbilling)
// }

func (q *Queries) ExecBASelectRefundBilling(ctx context.Context, arg ExecSPBASelectRefundBillingParams) ([]ExecSPBASelectRefundBillingRow, error) {
	rows, err := q.db.QueryContext(ctx, execBASelectRefundBilling, arg.SPAJId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecSPBASelectRefundBillingRow
	for rows.Next() {
		var i ExecSPBASelectRefundBillingRow
		if err := rows.Scan(
			&i.Pilih,	
			&i.BillingTransactionGuid,	
			&i.SPAJNo,	
			&i.BillingBatchId,	
			&i.BillingNo,	
			&i.BillingDescription,	
			&i.TransactionType,	
			&i.TransactionDate,	
			&i.NominalBilling,	
			&i.TotalFee,	
			&i.FeeBasedNISP,	
			&i.StatusBilling,	
			&i.BillingRemarks,	
			&i.ProductCode,	
			&i.BranchId,	
			&i.FeeBatchId,	
			&i.FeeTransactionDate,	
			&i.FeeStatus,	
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}